Rules:
  - SectorRule:
      # Rising yields
      # https://am.jpmorgan.com/lu/en/asset-management/per/insights/market-insights/on-the-minds-of-investors/growth-and-inflation-heating-up/
      strong_growing: [F, I]
      fair_growing: [E, M, Semi, Comod, EV]
      neutral: []
      fair_decline: [CD, H]
      strong_decline: [CS, R, U, C, T]
      weight: 1.5
  - CountryRule: # TODO: rename to RegionRule. Currently cannot use EU
      strong_growing: [china, HK, US]
      fair_growing: [FR, DE, NL, GB, KR, india, taiwan, japan, thailand, vietnam, greece]
      neutral: [russia]
      weight: 0.5
  - TerRule:
      weight: 0.1
  - PePsRule:
      weight: 1
  - DeclineRule:
      weight: 1
  - LtgRule:
      weight: 0.5
  - StgRule:
      weight: 1
